import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import astro from 'eslint-plugin-astro';
import vue from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
  {
    // `**/.astro/**` rather than `.astro/**`: ESLint's flat-config `ignores` isn't
    // recursive the way .gitignore is, so the un-prefixed form only ever matched
    // the project's own top-level cache. tests/fixtures/anon-read-path-violation is
    // a real Astro project in its own right (see anonymous-read-path.test.ts for
    // why it exists) and running a build against it generates the exact same
    // `.astro/types.d.ts` cache one level down, which would otherwise be linted as
    // if it were source. `node_modules/**` doesn't need the same treatment: ESLint
    // ignores every `node_modules` directory by default, at any depth.
    // `supabase/.temp/**` is the Supabase CLI's local scratch directory. Starting a
    // local stack writes the edge runtime's bundled `main/index.ts` there — third-party
    // generated code that produces ~190 lint errors and is deleted by `supabase stop`.
    // It is gitignored, but ESLint's flat config does not read .gitignore, so it has to
    // be named here too. Without it, `npm run lint` passes or fails according to
    // whether a database happens to be running; CI only escaped that because
    // `npm run check` runs before the stack starts, which is the kind of accidental
    // ordering that stops being true the moment somebody reorders a workflow.
    // `src/lib/database.types.ts` is generated by `npm run db:types` and committed
    // exactly as the Supabase CLI emits it — see the note in .prettierignore for why it
    // is not reformatted on the way in. It is ignored here because it is not ours to
    // edit: today it happens to produce zero lint errors (checked, not assumed, with
    // `eslint --no-ignore`), so this is not paying off a debt, it is refusing to take
    // one on the next time the generator's output shape moves. It is still type-checked:
    // `tsc --noEmit` reads it, which is the whole reason it exists.
    ignores: [
      'dist/**',
      '**/.astro/**',
      'node_modules/**',
      'src/assets/**',
      'src/lib/database.types.ts',
      'supabase/.temp/**',
      'supabase/.branches/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...astro.configs.recommended,
  ...vue.configs['flat/recommended'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    // vue-eslint-parser handles the SFC envelope but delegates <script lang="ts">
    // to an inner parser. Without this it chokes on the first type annotation.
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
        sourceType: 'module',
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  // Must stay last: switches off every stylistic rule that would fight Prettier.
  // ESLint owns correctness here, Prettier owns formatting.
  prettier,
];
