-- Deleting gear deletes it (PK-60): empty the trash into `status`, then drop
-- public.gear_items.deleted_at.
--
-- Two statements, and nothing else. No index to drop — 20260813000000_gear_closet.sql's
-- "Deliberately no new indexes" section (:123-146) lists deleted_at by name among the
-- columns it declines to index (:136), so nothing points at it. No policy, grant or
-- constraint change either: the table-level grants and owner-scoped policies in
-- 20260810120000_core_schema.sql are column-agnostic and never named it. And no trigger
-- change — gear_items_snapshot_before_delete is left exactly as it is, for reasons the
-- second section below is entirely about.

-- ---------------------------------------------------------------------------
-- Retired is the trash
-- ---------------------------------------------------------------------------
--
-- The product decision this column was built for has changed. Gear the user no longer owns
-- gets `status = 'retired'` (core_schema.sql:104) and stays in the closet, visibly marked
-- as retired. That is where "I got rid of this but I still want it in my history" lives,
-- and it is a state the owner can see, sort by and reverse with the same controls they use
-- for everything else. A soft delete added a SECOND kind of gone on top of it — invisible,
-- reached by a different gesture, recovered through a different route — and having two of
-- them was the confusion this ticket removes. Removing it means choosing one, and retired
-- is the one that survives, because it is the one already on screen. Delete now means what
-- the word means: the row leaves the database.

-- ---------------------------------------------------------------------------
-- Answering the three reasons in 20260813000000_gear_closet.sql
-- ---------------------------------------------------------------------------
--
-- That migration argued for this column at length and gave three numbered reasons. None of
-- them were wrong, and this is not a correction of them. Every one was an argument about
-- how to preserve an UNDO — so with no undo left to preserve, two are made moot rather
-- than refuted, and the third is a real cost that this migration accepts deliberately.
--
--   1. MOOT. set_row_timestamps() stamping a re-inserted row with a fresh created_at only
--      bites something that gets re-inserted. Nothing is: deleted gear does not come back,
--      so there is no second row whose date added could be wrong.
--
--   2. NOT MOOT — this is the price, and it should be read as one. The freeze that
--      gear_items_snapshot_before_delete (core_schema.sql:437-439) performs is irreversible
--      by design and remains so. Precisely: it fires BEFORE DELETE, once per row, and
--      writes the row into every referencing pack_item THAT HAS NO SNAPSHOT YET — a locked
--      pack froze its own copy at lock time and is left alone, which is what the trigger
--      function's `and snapshot is null` is for. It does not touch gear_item_id at all;
--      nulling that is the composite foreign key's `on delete set null (gear_item_id)`
--      (core_schema.sql:310-311), a separate mechanism that fires after. (deleteGearItems
--      in src/lib/gear/mutations.ts states the same two facts, and is the version to keep
--      this one in step with.) What soft delete really bought was keeping that trigger OUT
--      of ordinary use, reachable only by emptying the trash; this migration puts it back
--      into ordinary use, because deleting is now the ordinary gesture. Once Ref 37 (pack
--      composition) lands and packs genuinely reference closet gear, deleting an item will
--      rewrite every pack carrying it to a frozen snapshot with no gear_item_id, and
--      nothing anywhere can walk that back. That is a decision, not an oversight: the
--      weight this column used to carry now rests entirely on the confirmation the UI puts
--      in front of the user before the DELETE is issued.
--
--   3. MOOT, for the same reason as 1. Trash/undo needed the row to still exist somewhere
--      it could be found by id. There is no trash to find it from.

-- ---------------------------------------------------------------------------
-- Forward-only, and what that does to rows that are in the trash right now
-- ---------------------------------------------------------------------------
--
-- Dropping a column destroys its data and this project ships no down-migrations; recovery
-- from a bad migration is another migration (.github/workflows/deploy-staging.yml). Which
-- makes the order of the two statements below the whole of this section. A bare `drop
-- column` would hand every row currently holding a non-null deleted_at back to its owner
-- as an ordinary item marked `owned` — a silent un-delete of everything they deliberately
-- put in the trash, and the exact "two kinds of gone" confusion this ticket exists to
-- remove, arriving from the migration meant to remove it. So the UPDATE runs first and
-- moves those rows to where the section above argues the trash now is: `status =
-- 'retired'`, already one of the three values that column's own check constraint allows
-- (core_schema.sql:104), so this needs no constraint change and can never fail on one.
-- What the owner finds afterwards is a retired item — visible, correctly marked, and
-- reversible with the same status control as everything else in the closet.
--
-- THE MAPPING IS LOSSY, AND DELIBERATELY SO. "Trashed" and "retired" were genuinely
-- different states — one invisible and time-stamped, reached by a gesture that meant "get
-- this out of my sight", the other on screen and meaning "I no longer own this" — and the
-- row keeps no record of ever having been in the first. deleted_at's timestamp goes with
-- the column, and a row that was already retired before being trashed is afterwards
-- indistinguishable from one that was only ever retired. There is no state left to encode
-- the difference into, and inventing one would be re-adding this column under another
-- name. Nothing is hard-deleted on the way through: the ITEM survives every time, only the
-- record of the trash gesture does not.
--
-- WRITTEN FOR ANY DATABASE, NOT FOR TODAY'S. As it happens this UPDATE will match nothing
-- worth naming right now — hosted staging has had the column for less than a day and
-- production has never had it. That is a fact about one afternoon's deployment, not a
-- property of this file, and this file is permanent: it will run against any database that
-- ever acquires the column, including a restored snapshot, a stale local stack, or a
-- branch database rebuilt from this directory. Relying on "there are no such rows" would
-- be leaving the un-delete above in place and betting nobody ever replays this migration
-- somewhere it matters.
update public.gear_items
   set status = 'retired'
 where deleted_at is not null;

alter table public.gear_items
  drop column deleted_at;

-- No `comment on table` change: the table comment from core_schema.sql never mentioned this
-- column, and the `comment on column` goes with the column it was attached to.
